version: "2"
services:
  # api: 
  #   container_name: "api"
  #   command: npm start
  #   build: .
  #   ports:
  #     - "1337:1337"
  #   volumes:
  #     - .:/usr/src/app
  #   links:
  #     - redis
  redis:
    image: redis:4.0.1
    ports:
      - "6379:6379"
  myDb:
    container_name: "myDb"
    build: ./build/docker/db/
    environment: 
      MYSQL_USER: "db_user"
      MYSQL_PASSWORD: "db_user"
      MYSQL_ROOT_PASSWORD: "db_user"
      MYSQL_DATABASE: "myDb"
    ports:
      - "3306:3307"